
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: light_development

test:
  <<: *default
  database: light_test

production:
  <<: *default
  database: light_production
  username: lighter
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
